FORM_METADATA = [
    {
        "id": "criminal_record_req",
        "title_vi": "Tờ khai yêu cầu cấp Phiếu Lý lịch tư pháp",
        "title_en": "Criminal Record Certificate Request Form",
        "description": "Dùng cho cá nhân yêu cầu cấp Phiếu Lý lịch tư pháp (Thường là cho mục đích xin Giấy phép lao động hoặc đăng ký kết hôn).",
        "keywords": ["lylich", "lltp", "police check"],
        "docx_filename": "criminal_record_req.docx",
        "pdf_filename": "criminal_record_req.pdf",
    },
    {
        "id": "dl_exchange_form",
        "title_vi": "Đơn đề nghị đổi giấy phép lái xe",
        "title_en": "Driver's License Exchange Application Form",
        "description": "Bắt buộc. Dùng để nộp tại Sở Giao thông Vận tải khi đổi bằng lái xe nước ngoài sang bằng Việt Nam.",
        "keywords": ["laixe", "driver license", "gplx", "doi bang"],
        "docx_filename": "dl_exchange_form.docx",
        "pdf_filename": "dl_exchange_form.pdf",
    },
    {
        "id": "hospital_discharge_paper",
        "title_vi": "Giấy ra viện",
        "title_en": "Hospital Discharge Paper",
        "description": "Văn bản xác nhận việc bệnh nhân đã được xuất viện. Thường cần cho việc thanh toán bảo hiểm hoặc chứng minh tình trạng sức khỏe.",
        "keywords": ["suckhoe", "health", "bhyt", "insurance"],
        "docx_filename": "hospital_discharge_paper.docx",
        "pdf_filename": "hospital_discharge_paper.pdf",
    },
    {
        "id": "ls_hph_consular_legalization",
        "title_vi": "Tờ khai Hợp pháp hóa/Chứng nhận Lãnh sự",
        "title_en": "Consular Legalization/Authentication Application (LS/HPH-2012/TK)",
        "description": "Dùng để nộp tại Bộ Ngoại giao (Cục Lãnh sự) khi hợp pháp hóa giấy tờ do nước ngoài cấp để sử dụng tại Việt Nam (VD: Giấy khai sinh, Giấy độc thân).",
        "keywords": ["hophaphoa", "lãnh sự", "legalization", "consular"],
        "docx_filename": "ls_hph_consular_legalization.docx", 
        "pdf_filename": "ls_hph_consular_legalization.pdf",
    },
    {
        "id": "marriage_reg_form",
        "title_vi": "Tờ khai Đăng ký kết hôn",
        "title_en": "Marriage Registration Form",
        "description": "Dùng cho thủ tục đăng ký kết hôn giữa công dân Việt Nam và người nước ngoài tại Sở Tư pháp.",
        "keywords": ["ket hon", "marriage", "tư pháp"],
        "docx_filename": "marriage_reg_form.docx",
        "pdf_filename": "marriage_reg_form.pdf",
    },
    {
        "id": "na1_visa_app",
        "title_vi": "Tờ khai đề nghị cấp, bổ sung, sửa đổi thị thực",
        "title_en": "Visa Application Form (NA1)",
        "description": "Dùng cho người nước ngoài đề nghị cấp thị thực (visa) tại cửa khẩu hoặc Đại sứ quán.",
        "keywords": ["visa", "thị thực", "na1", "nhapcanh"],
        "docx_filename": "na1_visa_app.docx",
        "pdf_filename": "na1_visa_app.pdf",
    },
    {
        "id": "na3_relative_guarantee",
        "title_vi": "Đơn bảo lãnh cho người thân (NA3)",
        "title_en": "Personal Guarantee/Sponsorship Form (NA3)",
        "description": "Do cá nhân (người Việt) bảo lãnh người thân nước ngoài nhập cảnh Việt Nam.",
        "keywords": ["baolanh", "na3", "thamthan", "sponsorship"],
        "docx_filename": "na3_relative_guarantee.docx",
        "pdf_filename": "na3_relative_guarantee.pdf",
    },
    {
        "id": "na5_visa_extension",
        "title_vi": "Tờ khai đề nghị gia hạn tạm trú",
        "title_en": "Temporary Residence Extension Application (NA5)",
        "description": "Bắt buộc. Dùng để xin gia hạn visa hoặc tạm trú tại Cục Quản lý Xuất nhập cảnh.",
        "keywords": ["giahan", "na5", "extension", "tam tru"],
        "docx_filename": "na5_visa_extension.docx",
        "pdf_filename": "na5_visa_extension.pdf",
    },
    {
        "id": "na8_trc_application",
        "title_vi": "Đơn đề nghị cấp Thẻ tạm trú (TRC)",
        "title_en": "Temporary Residence Card Application (NA8)",
        "description": "Do người nước ngoài khai để xin cấp thẻ tạm trú lần đầu tại Việt Nam.",
        "keywords": ["thetam tru", "trc", "na8"],
        "docx_filename": "na8_trc_application.docx",
        "pdf_filename": "na8_trc_application.pdf",
    },
    {
        "id": "na9_trc_renew",
        "title_vi": "Đơn đề nghị cấp lại/gia hạn Thẻ tạm trú (TRC)",
        "title_en": "Temporary Residence Card Renewal/Re-issuance Application (NA9)",
        "description": "Dùng khi thẻ tạm trú cũ sắp hết hạn hoặc bị mất.",
        "keywords": ["giahan trc", "na9", "trc renewal"],
        "docx_filename": "na9_trc_renew.docx",
        "pdf_filename": "na9_trc_renew.pdf",
    },
]